### ISSUE TITLE
efmaral on windows

### ISSUE THREAD

**Issue by VarvaraHuts** [robertostling/efmaral#3]
Is efmaral supported on Windows? I can't find any relevant instructions.

**Comment by robertostling** [comment]
I don't see any reason why it wouldn't work under e.g. Cygwin, but I'm not aware of anyone actually trying this.

**Comment by VarvaraHuts** [comment]
ok, thanks.

**Comment by VarvaraHuts** [comment]
I've installed efmaral in Cygwin, but I can't find 'cyalign.pyx'. Makefile fails with error 'No rule to make target 'cyalign.pyx'.

**Comment by robertostling** [comment]
The Makefile is deprecated (removed in fa0ab1e), install with setup.py directly as detailed in the README.
