### ISSUE TITLE
How can I use the output-prob flie

### ISSUE THREAD

**Issue by LucianZhan** [robertostling/efmaral#6]
I added the "--output-prob" parameter, but I can't figure out how to use it.  How can I get word alignment results with probability? (like "word1  word2   0.01")

**Comment by robertostling** [comment]
The file written by the --output-prob argument is a Python pickle file, containing a tuple of length N (number of parallel sentences in input) where each element is a 1D numpy ndarray of shape S+1*D where S is the source language sentence length and D is the target language sentence length. Logically it is a flattened S+1 times D matrix containing alignment probabilities. The extra dimension on the source side is for NULL alignments.

I admit this is not a very convenient file format, it is just a dump of the internal representation within efmaral. However, it should be fairly simple to convert it to a text-based format of your liking.
